modLoader = "javafml"
loaderVersion = "*"
license = "GPL-3"
issueTrackerURL="https://github.com/PandaDap2006/Pandas-Extra-Details/issues"

[[mods]]
	modId = "extra_details"
	version = "${version}"
	displayName = "Panda's Extra Detail's"
	authors = "Panda Mods/The Panda Oliver"
	description = "A mod that adds small details and animations to Minecraft"
	logoFile = "icon.png"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "The Panda Oliver"
logoFile = "assets/extra_details/icon.png"
description = "${description}"

[[dependencies.extra_details]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.extra_details]]
modId = "minecraft"
mandatory = true
versionRange = "${compatible_forgemc_versions}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.extra_details]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.extra_details]]
modId = "pandalib"
mandatory = true
versionRange = "[0.3,)"
ordering = "AFTER"
side = "CLIENT"